Codelist Management update v2.02
IATI/IATI-Standard-SSOT pull request #308
Opened 2019-04-23 09:27 UTC by Ocre42

2019-04-23 14:05 UTC, sargentfrancesca requested changes

2019-04-23 14:05 UTC, sargentfrancesca commented on templates/en/codelist.rst
> -{% if embedded %}
As per [this review](https://github.com/IATI/IATI-Standard-SSOT/pull/309#pullrequestreview-229561208), just remove the template variable from `gen.py`

2019-04-24 10:25 UTC, amy-silcock approved these changes
Looks good - I changed a small bit of wording.

2019-04-24 10:50 UTC, amy-silcock approved these changes
Looks good

2019-04-25 10:08 UTC, sargentfrancesca approved these changes

2019-04-25 10:08 UTC, merged