Codelist Management update v2.01
IATI/IATI-Standard-SSOT pull request #309
Opened 2019-04-23 09:27 UTC by Ocre42

2019-04-23 13:58 UTC, sargentfrancesca requested changes

2019-04-23 13:58 UTC, sargentfrancesca commented on templates/en/codelist.rst
> -{% if embedded %}
if `embedded` property isn't used elsewhere, it can be removed from `gen.py`

2019-04-23 13:58 UTC, sargentfrancesca commented on templates/en/codelist.rst
> -{% if embedded %}
actually, it only needs to be removed from the 'context' - the os.path is used to determine the git url, which we still need: https://github.com/IATI/IATI-Standard-SSOT/blob/ac0a800f9070c67eac13770bcae5521934ea2419/gen.py#L552

2019-04-24 10:26 UTC, amy-silcock approved these changes
One small change made - looks good

2019-04-25 10:08 UTC, sargentfrancesca approved these changes

2019-04-25 10:08 UTC, merged