Print rule text with rule numbers 202
IATI/IATI-Standard-SSOT pull request #385
Opened 2021-12-08 18:23 UTC by akmiller01

2021-12-09 14:05 UTC, nosvalds requested changes
Spot checking here running locally. I'm seeing an issue with this file:
`docs/en/organisation-standard/iati-organisations/iati-organisation/recipient-org-budget/recipient-org.rst`

```
`1.17.1 <https://github.com/IATI/IATI-Rulesets/blob/v2.03/validatorV2/rulesets/standard.json#L978>`_: The recipient organisation identifier should not start or end with spaces or newlines.
```

The link doesn't get you to 1.17.1.

2021-12-09 14:29 UTC, akmiller01 commented
@nosvalds those links come from the IATI-Ruleset repos, so it looks like we'll need to change the `default_url` back to the base `version-2.0X` branches: https://github.com/IATI/IATI-Rulesets/blob/version-2.03/iatirulesets/text.py#L25-L38

2021-12-10 10:53 UTC, nosvalds approved these changes

2021-12-10 14:16 UTC, PetyaKangalova approved these changes

2022-01-11 13:30 UTC, merged