Add documentation for some gen.py functions
IATI/IATI-Standard-SSOT pull request #89
Opened 2017-07-18 12:06 UTC by dalepotter

2017-07-22 00:50 UTC, allthatilk requested changes

2017-07-22 00:50 UTC, allthatilk commented on gen.py
> +        standard (str): Unknown
standard (str): 'activity-standard' presumably a tag indicating that it is working from the Activity Standard

2017-07-22 00:50 UTC, allthatilk commented on gen.py
> +        mapping (list): Unknown
mapping (dict): A dictionary containing tuples in the format key:[value] that groups Element tags in the Standard by relevant category. eg. `u'activity-file': [u'iati-activities', u'iati-activities/iati-activity']`

2017-07-22 00:50 UTC, allthatilk commented on gen.py
> +        path (str): Unknown
path (str): Seems to return strings for xpath queries. eg. `'other-identifier'` or `'activity-date/narrative'`

2017-07-22 00:50 UTC, allthatilk commented on gen.py
> +        generator or str: Unknown
generator (str): Generates a series of unicode strings for Activity Elements in Schema (I think).

2017-07-22 00:50 UTC, allthatilk commented on gen.py
> +            path (str): Unused.
If it's unused is it okay to remove the arg?

2018-10-26 15:35 UTC, samuele-mattiuzzo approved these changes

2018-10-26 15:35 UTC, merged